export interface CuratedEmoji {
  readonly char: string;   // the emoji character(s)
  readonly name: string;   // lowercase, e.g. "thumbs up"
  readonly group: string;  // e.g. "Smileys", "Gestures", "Hearts", ...
}

/** The curated set. ~200 entries. */
export const CURATED_EMOJI: readonly CuratedEmoji[] = [
  // Smileys (30)
  { char: '\u{1F600}', name: 'grinning face', group: 'Smileys' },
  { char: '\u{1F601}', name: 'beaming face with smiling eyes', group: 'Smileys' },
  { char: '\u{1F604}', name: 'grinning face with smiling eyes', group: 'Smileys' },
  { char: '\u{1F602}', name: 'face with tears of joy', group: 'Smileys' },
  { char: '\u{1F923}', name: 'rolling on the floor laughing', group: 'Smileys' },
  { char: '\u{1F60A}', name: 'smiling face with smiling eyes', group: 'Smileys' },
  { char: '\u{1F609}', name: 'winking face', group: 'Smileys' },
  { char: '\u{1F60D}', name: 'smiling face with heart-eyes', group: 'Smileys' },
  { char: '\u{1F970}', name: 'smiling face with hearts', group: 'Smileys' },
  { char: '\u{1F60E}', name: 'smiling face with sunglasses', group: 'Smileys' },
  { char: '\u{1F929}', name: 'star-struck', group: 'Smileys' },
  { char: '\u{1F607}', name: 'smiling face with halo', group: 'Smileys' },
  { char: '\u{1F642}', name: 'slightly smiling face', group: 'Smileys' },
  { char: '\u{1F605}', name: 'grinning face with sweat', group: 'Smileys' },
  { char: '\u{1F60F}', name: 'smirking face', group: 'Smileys' },
  { char: '\u{1F62E}', name: 'face with open mouth', group: 'Smileys' },
  { char: '\u{1F914}', name: 'thinking face', group: 'Smileys' },
  { char: '\u{1F917}', name: 'hugging face', group: 'Smileys' },
  { char: '\u{1F644}', name: 'face with rolling eyes', group: 'Smileys' },
  { char: '\u{1F634}', name: 'sleeping face', group: 'Smileys' },
  { char: '\u{1F62C}', name: 'grimacing face', group: 'Smileys' },
  { char: '\u{1F910}', name: 'zipper-mouth face', group: 'Smileys' },
  { char: '\u{1F92B}', name: 'shushing face', group: 'Smileys' },
  { char: '\u{1F973}', name: 'partying face', group: 'Smileys' },
  { char: '✨', name: 'sparkles', group: 'Smileys' },
  { char: '\u{1F525}', name: 'fire', group: 'Smileys' },
  { char: '⭐', name: 'star', group: 'Smileys' },
  { char: '\u{1F4AF}', name: 'hundred points', group: 'Smileys' },
  { char: '\u{1F389}', name: 'party popper', group: 'Smileys' },
  { char: '\u{1F31F}', name: 'glowing star', group: 'Smileys' },

  // People (15)
  { char: '\u{1F64B}', name: 'person raising hand', group: 'People' },
  { char: '\u{1F481}', name: 'person tipping hand', group: 'People' },
  { char: '\u{1F647}', name: 'person bowing', group: 'People' },
  { char: '\u{1F464}', name: 'bust in silhouette', group: 'People' },
  { char: '\u{1F465}', name: 'busts in silhouette', group: 'People' },
  { char: '\u{1F9E0}', name: 'brain', group: 'People' },
  { char: '\u{1F440}', name: 'eyes', group: 'People' },
  { char: '\u{1F9D1}', name: 'person', group: 'People' },
  { char: '\u{1F476}', name: 'baby', group: 'People' },
  { char: '\u{1F469}', name: 'woman', group: 'People' },
  { char: '\u{1F468}', name: 'man', group: 'People' },
  { char: '\u{1F9D2}', name: 'child', group: 'People' },
  { char: '\u{1F474}', name: 'old man', group: 'People' },
  { char: '\u{1F475}', name: 'old woman', group: 'People' },
  { char: '\u{1F9D4}', name: 'bearded person', group: 'People' },

  // Gestures (20)
  { char: '\u{1F44D}', name: 'thumbs up', group: 'Gestures' },
  { char: '\u{1F44E}', name: 'thumbs down', group: 'Gestures' },
  { char: '\u{1F44C}', name: 'ok hand', group: 'Gestures' },
  { char: '✌', name: 'victory hand', group: 'Gestures' },
  { char: '\u{1F91E}', name: 'crossed fingers', group: 'Gestures' },
  { char: '✊', name: 'raised fist', group: 'Gestures' },
  { char: '\u{1F91D}', name: 'handshake', group: 'Gestures' },
  { char: '\u{1F64F}', name: 'folded hands', group: 'Gestures' },
  { char: '\u{1F4AA}', name: 'muscle', group: 'Gestures' },
  { char: '☝', name: 'point up', group: 'Gestures' },
  { char: '\u{1F449}', name: 'point right', group: 'Gestures' },
  { char: '\u{1F447}', name: 'point down', group: 'Gestures' },
  { char: '\u{1F448}', name: 'point left', group: 'Gestures' },
  { char: '\u{1F44B}', name: 'wave', group: 'Gestures' },
  { char: '\u{1F919}', name: 'call me hand', group: 'Gestures' },
  { char: '\u{1F590}', name: 'hand with fingers splayed', group: 'Gestures' },
  { char: '\u{1F44F}', name: 'clapping hands', group: 'Gestures' },
  { char: '\u{1F64C}', name: 'raising hands', group: 'Gestures' },
  { char: '\u{1F91C}', name: 'right-facing fist', group: 'Gestures' },
  { char: '\u{1F91B}', name: 'left-facing fist', group: 'Gestures' },

  // Hearts (15)
  { char: '❤', name: 'red heart', group: 'Hearts' },
  { char: '\u{1F9E1}', name: 'orange heart', group: 'Hearts' },
  { char: '\u{1F49B}', name: 'yellow heart', group: 'Hearts' },
  { char: '\u{1F49A}', name: 'green heart', group: 'Hearts' },
  { char: '\u{1F499}', name: 'blue heart', group: 'Hearts' },
  { char: '\u{1F49C}', name: 'purple heart', group: 'Hearts' },
  { char: '\u{1F494}', name: 'broken heart', group: 'Hearts' },
  { char: '❣', name: 'heart exclamation', group: 'Hearts' },
  { char: '\u{1F495}', name: 'two hearts', group: 'Hearts' },
  { char: '\u{1F49E}', name: 'revolving hearts', group: 'Hearts' },
  { char: '\u{1F493}', name: 'beating heart', group: 'Hearts' },
  { char: '\u{1F497}', name: 'growing heart', group: 'Hearts' },
  { char: '\u{1F496}', name: 'sparkling heart', group: 'Hearts' },
  { char: '\u{1F498}', name: 'heart with arrow', group: 'Hearts' },
  { char: '\u{1F5A4}', name: 'black heart', group: 'Hearts' },

  // Objects (55)
  { char: '\u{1F4BB}', name: 'laptop', group: 'Objects' },
  { char: '\u{1F4F1}', name: 'mobile phone', group: 'Objects' },
  { char: '\u{1F4A1}', name: 'light bulb', group: 'Objects' },
  { char: '\u{1F4DA}', name: 'books', group: 'Objects' },
  { char: '\u{1F4C5}', name: 'calendar', group: 'Objects' },
  { char: '\u{1F4C8}', name: 'chart increasing', group: 'Objects' },
  { char: '\u{1F3C6}', name: 'trophy', group: 'Objects' },
  { char: '\u{1F947}', name: 'first place medal', group: 'Objects' },
  { char: '\u{1F680}', name: 'rocket', group: 'Objects' },
  { char: '\u{1F3AF}', name: 'direct hit', group: 'Objects' },
  { char: '\u{1F4BC}', name: 'briefcase', group: 'Objects' },
  { char: '\u{1F4B0}', name: 'money bag', group: 'Objects' },
  { char: '\u{1F4E3}', name: 'megaphone', group: 'Objects' },
  { char: '\u{1F514}', name: 'bell', group: 'Objects' },
  { char: '\u{1F4CC}', name: 'pushpin', group: 'Objects' },
  { char: '\u{1F517}', name: 'link', group: 'Objects' },
  { char: '⚙', name: 'gear', group: 'Objects' },
  { char: '\u{1F527}', name: 'wrench', group: 'Objects' },
  { char: '\u{1F528}', name: 'hammer', group: 'Objects' },
  { char: '\u{1F511}', name: 'key', group: 'Objects' },
  { char: '\u{1F512}', name: 'locked', group: 'Objects' },
  { char: '\u{1F58A}', name: 'pen', group: 'Objects' },
  { char: '\u{1F4DD}', name: 'memo', group: 'Objects' },
  { char: '\u{1F4CB}', name: 'clipboard', group: 'Objects' },
  { char: '\u{1F516}', name: 'bookmark', group: 'Objects' },
  { char: '\u{1F4E6}', name: 'package', group: 'Objects' },
  { char: '\u{1F5A5}', name: 'desktop computer', group: 'Objects' },
  { char: '⌨', name: 'keyboard', group: 'Objects' },
  { char: '\u{1F5B1}', name: 'computer mouse', group: 'Objects' },
  { char: '\u{1F4CA}', name: 'bar chart', group: 'Objects' },
  { char: '\u{1F4C9}', name: 'chart decreasing', group: 'Objects' },
  { char: '\u{1F4B9}', name: 'chart increasing with yen', group: 'Objects' },
  { char: '\u{1F4E1}', name: 'satellite antenna', group: 'Objects' },
  { char: '\u{1F399}', name: 'studio microphone', group: 'Objects' },
  { char: '\u{1F3A7}', name: 'headphone', group: 'Objects' },
  { char: '\u{1F4F7}', name: 'camera', group: 'Objects' },
  { char: '\u{1F50D}', name: 'magnifying glass', group: 'Objects' },
  { char: '\u{1F48E}', name: 'gem stone', group: 'Objects' },
  { char: '\u{1F3C5}', name: 'sports medal', group: 'Objects' },
  { char: '\u{1F393}', name: 'graduation cap', group: 'Objects' },
  { char: '\u{1F4E2}', name: 'loudspeaker', group: 'Objects' },
  { char: '\u{1F5D3}', name: 'spiral calendar', group: 'Objects' },
  { char: '\u{1F5C2}', name: 'card index dividers', group: 'Objects' },
  { char: '\u{1F4C1}', name: 'file folder', group: 'Objects' },
  { char: '\u{1F4C2}', name: 'open file folder', group: 'Objects' },
  { char: '\u{1F5C3}', name: 'card file box', group: 'Objects' },
  { char: '\u{1F4C4}', name: 'page facing up', group: 'Objects' },
  { char: '\u{1F4C3}', name: 'page with curl', group: 'Objects' },
  { char: '\u{1F4D1}', name: 'bookmark tabs', group: 'Objects' },
  { char: '\u{1F510}', name: 'locked with key', group: 'Objects' },
  { char: '\u{1F513}', name: 'unlocked', group: 'Objects' },
  { char: '\u{1F4AC}', name: 'speech balloon', group: 'Objects' },
  { char: '\u{1F4CD}', name: 'round pushpin', group: 'Objects' },
  { char: '\u{1F5D2}', name: 'spiral notepad', group: 'Objects' },
  { char: '\u{1F50F}', name: 'locked with pen', group: 'Objects' },

  // Symbols (35)
  { char: '✅', name: 'check mark button', group: 'Symbols' },
  { char: '❌', name: 'cross mark', group: 'Symbols' },
  { char: '⚠', name: 'warning', group: 'Symbols' },
  { char: '❗', name: 'exclamation mark', group: 'Symbols' },
  { char: '❓', name: 'question mark', group: 'Symbols' },
  { char: '➕', name: 'plus', group: 'Symbols' },
  { char: '➖', name: 'minus', group: 'Symbols' },
  { char: '♾', name: 'infinity', group: 'Symbols' },
  { char: '♻', name: 'recycling symbol', group: 'Symbols' },
  { char: '©', name: 'copyright', group: 'Symbols' },
  { char: '®', name: 'registered', group: 'Symbols' },
  { char: '™', name: 'trade mark', group: 'Symbols' },
  { char: '✔', name: 'check mark', group: 'Symbols' },
  { char: '✖', name: 'multiplication x', group: 'Symbols' },
  { char: '\u{1F534}', name: 'red circle', group: 'Symbols' },
  { char: '\u{1F7E2}', name: 'green circle', group: 'Symbols' },
  { char: '\u{1F535}', name: 'blue circle', group: 'Symbols' },
  { char: '⚡', name: 'lightning bolt', group: 'Symbols' },
  { char: '\u{1F4AB}', name: 'dizzy', group: 'Symbols' },
  { char: '\u{1F300}', name: 'cyclone', group: 'Symbols' },
  { char: '⭕', name: 'hollow red circle', group: 'Symbols' },
  { char: '\u{1F536}', name: 'large orange diamond', group: 'Symbols' },
  { char: '\u{1F537}', name: 'large blue diamond', group: 'Symbols' },
  { char: '\u{1F538}', name: 'small orange diamond', group: 'Symbols' },
  { char: '\u{1F539}', name: 'small blue diamond', group: 'Symbols' },
  { char: '▪', name: 'black small square', group: 'Symbols' },
  { char: '▫', name: 'white small square', group: 'Symbols' },
  { char: '\u{1F53A}', name: 'red triangle pointed up', group: 'Symbols' },
  { char: '\u{1F53B}', name: 'red triangle pointed down', group: 'Symbols' },
  { char: '\u{1F4A0}', name: 'diamond with a dot', group: 'Symbols' },
  { char: '\u{1F518}', name: 'radio button', group: 'Symbols' },
  { char: '\u{1F532}', name: 'black square button', group: 'Symbols' },
  { char: '\u{1F533}', name: 'white square button', group: 'Symbols' },
  { char: '⚪', name: 'white circle', group: 'Symbols' },
  { char: '⚫', name: 'black circle', group: 'Symbols' },

  // Arrows & Numbers (30)
  { char: '⬅', name: 'left arrow', group: 'Arrows & Numbers' },
  { char: '➡', name: 'right arrow', group: 'Arrows & Numbers' },
  { char: '⬆', name: 'up arrow', group: 'Arrows & Numbers' },
  { char: '⬇', name: 'down arrow', group: 'Arrows & Numbers' },
  { char: '↩', name: 'right arrow curving left', group: 'Arrows & Numbers' },
  { char: '↪', name: 'left arrow curving right', group: 'Arrows & Numbers' },
  { char: '↗', name: 'up-right arrow', group: 'Arrows & Numbers' },
  { char: '↘', name: 'down-right arrow', group: 'Arrows & Numbers' },
  { char: '↙', name: 'down-left arrow', group: 'Arrows & Numbers' },
  { char: '↖', name: 'up-left arrow', group: 'Arrows & Numbers' },
  { char: '↕', name: 'up-down arrow', group: 'Arrows & Numbers' },
  { char: '↔', name: 'left-right arrow', group: 'Arrows & Numbers' },
  { char: '\u{1F519}', name: 'back arrow', group: 'Arrows & Numbers' },
  { char: '\u{1F51A}', name: 'end arrow', group: 'Arrows & Numbers' },
  { char: '\u{1F51B}', name: 'on arrow', group: 'Arrows & Numbers' },
  { char: '\u{1F51C}', name: 'soon arrow', group: 'Arrows & Numbers' },
  { char: '\u{1F51D}', name: 'top arrow', group: 'Arrows & Numbers' },
  { char: '0️⃣', name: 'keycap 0', group: 'Arrows & Numbers' },
  { char: '1️⃣', name: 'keycap 1', group: 'Arrows & Numbers' },
  { char: '2️⃣', name: 'keycap 2', group: 'Arrows & Numbers' },
  { char: '3️⃣', name: 'keycap 3', group: 'Arrows & Numbers' },
  { char: '4️⃣', name: 'keycap 4', group: 'Arrows & Numbers' },
  { char: '5️⃣', name: 'keycap 5', group: 'Arrows & Numbers' },
  { char: '6️⃣', name: 'keycap 6', group: 'Arrows & Numbers' },
  { char: '7️⃣', name: 'keycap 7', group: 'Arrows & Numbers' },
  { char: '8️⃣', name: 'keycap 8', group: 'Arrows & Numbers' },
  { char: '9️⃣', name: 'keycap 9', group: 'Arrows & Numbers' },
  { char: '#️⃣', name: 'keycap hash', group: 'Arrows & Numbers' },
  { char: '*️⃣', name: 'keycap asterisk', group: 'Arrows & Numbers' },
  { char: '\u{1F504}', name: 'counterclockwise arrows', group: 'Arrows & Numbers' },
];

/** The group names in display order. */
export const EMOJI_GROUPS: readonly string[] = [
  'Smileys',
  'People',
  'Gestures',
  'Hearts',
  'Objects',
  'Symbols',
  'Arrows & Numbers',
];

/** Set of all valid emoji chars for the validator. Single source of truth. */
export const CURATED_EMOJI_CHARS: ReadonlySet<string> = new Set(
  CURATED_EMOJI.map(e => e.char)
);
